Loaded module: cuda/11.3
Loaded dependency [python3/3.7.11]: gcc/10.3.0-binutils-2.36.1
Loaded module: python3/3.7.11

Loading python3/3.7.11
  Loading requirement: gcc/10.3.0-binutils-2.36.1
Loaded dependency [numpy/1.21.1-python-3.7.11-openblas-0.3.17]: openblas/0.3.17
Loaded dependency [pandas/1.3.1-python-3.7.11]: numpy/1.21.1-python-3.7.11-openblas-0.3.17
Loaded module: pandas/1.3.1-python-3.7.11

Loading pandas/1.3.1-python-3.7.11
  Loading requirement: openblas/0.3.17
    numpy/1.21.1-python-3.7.11-openblas-0.3.17
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
  WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
  distutils: /zhome/4c/8/164840/.local/include/python3.7m/pip
  sysconfig: /zhome/4c/8/164840/.local/include/python3.7/pip
  WARNING: Additional context:
  user = True
  home = None
  root = None
  prefix = None
  WARNING: The scripts pip, pip3, pip3.10 and pip3.7 are installed in '/zhome/4c/8/164840/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
ERROR: Could not find a version that satisfies the requirement subprocess (from versions: none)
ERROR: No matching distribution found for subprocess
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /appl/python/3.7.11/include/python3.7m/UNKNOWN
sysconfig: /appl/python/3.7.11/include/python3.7m
WARNING: Additional context:
user = False
home = None
root = None
prefix = None
WARNING: Value for scheme.headers does not match. Please report this to <https://github.com/pypa/pip/issues/9617>
distutils: /zhome/4c/8/164840/.local/include/python3.7m/UNKNOWN
sysconfig: /zhome/4c/8/164840/.local/include/python3.7
WARNING: Additional context:
user = True
home = None
root = None
prefix = None
WARNING: You are using pip version 21.1; however, version 22.1.2 is available.
You should consider upgrading via the '/appl/python/3.7.11/bin/python3 -m pip install --upgrade pip' command.
